version: '2'
services:
  postgres:
    image: postgres:9.6.6
    environment:
      POSTGRES_USER: spiuser
      POSTGRES_PASSWORD: spiuser
      POSTGRES_DB: spicinemas
    ports:
      - "5435:5432"
  nginx:
    build:
      context: .
      dockerfile: Nginx-Dockerfile
    volumes:
      - $PWD/static-assets:/usr/share/nginx/html
    ports:
      - "8080:80"
  api-service:
    depends_on:
      - postgres  
    build:
      context: .
      dockerfile: API-Dockerfile
    ports:
     - "9090:9090"
